# Generated by Django 4.1.7 on 2023-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
