# Generated by Django 4.1.7 on 2023-04-09 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_cartitem_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=225)),
                ('shipping_address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('discount', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('create_at', models.DateField()),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('Cancel Payment', 'Cancel Payment'), ('Payment Received', 'Payment Received'), ('Order in progress', 'Order in progress'), ('Order Received', 'Order Received')], default='pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('Paystack', 'Paystack'), ('Transfer', 'Transfer')], default='Paystack', max_length=50)),
                ('payment_complete', models.BooleanField(default=False)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
